tel: "+17865555555"
tel_display: 786 555 5555
seo:
  tagline: Live the dream in an old-style English Cottage
location:
  country: England
  locality: Leamington Spa
  region: Warwickshire
  street_address: 1234 Roundabout Way
